# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtWebEngineWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.browser = QWebEngineView()
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background: rgb(59, 59, 59)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.urlBar = QtWidgets.QLineEdit(self.centralwidget)
        self.urlBar.setGeometry(QtCore.QRect(80, 0, 981, 20))
        self.urlBar.returnPressed.connect(self.navigate_to_url)

        def navigate_to_url(self):
            url = self.url_bar.text()
            self.browser.setUrl(QUrl(url))
        self.urlBar.setStyleSheet("QLineEdit {\n"
"    background: rgb(0, 0, 0);\n"
"    border: 1px solid #00000;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    color: #FFF\n"
"}")
        self.urlBar.setObjectName("urlBar")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(0, 0, 21, 23))
        self.homeButton.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 0, 0);\n"
"    border: 2px solid #00000;\n"
"    border-radius: 8px;\n"
"    padding: 2px\n"
"    \n"
"}")
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Travis\'s Files/Downloads/house-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setObjectName("homeButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 0, 21, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 0, 0);\n"
"    border: 2px solid #00000;\n"
"    border-radius: 8px;\n"
"    padding: 2px\n"
"    \n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Travis\'s Files/Downloads/arrow-118-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 0, 21, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 0, 0);\n"
"    border: 2px solid #00000;\n"
"    border-radius: 8px;\n"
"    padding: 2px\n"
"    \n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Travis\'s Files/Downloads/arrow-18-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 0, 21, 23))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 0, 0);\n"
"    border: 2px solid #00000;\n"
"    border-radius: 8px;\n"
"    padding: 2px\n"
"    \n"
"}")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Travis\'s Files/Downloads/refresh-2-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget = self.browser
        self.widget.setGeometry(QtCore.QRect(10, 30, 1041, 771))
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Browser"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
